[package]
name = "ruuvitag-listener"
version = "0.1.0"
authors = ["Mike Walters <mike@flomp.net>"]
edition = "2018"

[dependencies]
ble-advert-struct = { git = "https://github.com/miek/ble-advert-struct.git" }
byteorder = "1"
derive_more = "0.14.0"
rumqtt = "0.30.1"
serde_json = "1.0.39"
